import 'package:flutter/material.dart';
void main()=>runApp(const UcariApp());
const gold=Color(0xFFD7AA43),ink=Color(0xFF17130F),cream=Color(0xFFF8F4EC);
class UcariApp extends StatelessWidget{const UcariApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'UÇARI Yayınevi',theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:cream,colorScheme:ColorScheme.fromSeed(seedColor:gold)),home:const Shell());}
class Book{final String title,author,category;final int price;const Book(this.title,this.author,this.category,this.price);}const books=[Book('Kayıp Zaman','Ahmet Demir','Roman',280),Book('Sessiz Nehir','Elif Kaya','Roman',240),Book('Dağın Ötesi','Murat Arslan','Macera',300),Book('Gölgedeki Işık','Zeynep Yıldız','Şiir',220)];
class Shell extends StatefulWidget{const Shell({super.key});@override State<Shell> createState()=>_ShellState();}
class _ShellState extends State<Shell>{int index=0;@override Widget build(BuildContext c){final pages=[const HomePage(),const BooksPage(),const AuthorPage(),const CartPage(),const AccountPage()];return Scaffold(body:SafeArea(child:pages[index]),bottomNavigationBar:NavigationBar(selectedIndex:index,indicatorColor:gold.withValues(alpha:.25),onDestinationSelected:(v)=>setState(()=>index=v),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),label:'Ana Sayfa'),NavigationDestination(icon:Icon(Icons.menu_book_outlined),label:'Kitaplar'),NavigationDestination(icon:Icon(Icons.edit_note),label:'Yazar Ol'),NavigationDestination(icon:Icon(Icons.shopping_cart_outlined),label:'Sepet'),NavigationDestination(icon:Icon(Icons.person_outline),label:'Hesabım')]));}}
class Header extends StatelessWidget{final String title;const Header(this.title,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(20),child:Row(children:[const CircleAvatar(backgroundColor:ink,child:Icon(Icons.auto_stories,color:gold)),const SizedBox(width:10),Expanded(child:Text(title,style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))),const Icon(Icons.notifications_none)]));}
class HomePage extends StatelessWidget{const HomePage({super.key});@override Widget build(BuildContext c)=>ListView(children:[const Header('UÇARI YAYINEVİ'),const Padding(padding:EdgeInsets.symmetric(horizontal:20),child:SearchBar(hintText:'Kitap, yazar veya kategori ara...',leading:Icon(Icons.search))),Container(margin:const EdgeInsets.all(20),padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:ink,borderRadius:BorderRadius.circular(20)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Her hikaye,\nbir iz bırakır.',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.bold)),SizedBox(height:12),Text('UÇARI YAYINEVİ',style:TextStyle(color:gold))])),const Padding(padding:EdgeInsets.all(20),child:Text('Yeni Çıkanlar',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold))),...books.map((b)=>BookTile(b))]);}
class BookTile extends StatelessWidget{final Book book;const BookTile(this.book,{super.key});@override Widget build(BuildContext c)=>ListTile(onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>BookDetail(book))),leading:Container(width:48,height:64,color:ink,child:const Icon(Icons.book,color:gold)),title:Text(book.title),subtitle:Text('${book.author} • ${book.category}'),trailing:Text('₺${book.price}',style:const TextStyle(fontWeight:FontWeight.bold)));}
class BooksPage extends StatelessWidget{const BooksPage({super.key});@override Widget build(BuildContext c)=>Column(children:[const Header('Kitaplar'),const Padding(padding:EdgeInsets.symmetric(horizontal:20),child:SearchBar(hintText:'Kitap veya yazar ara...',leading:Icon(Icons.search),trailing:[Icon(Icons.tune)])),Expanded(child:ListView(children:books.map((b)=>BookTile(b)).toList()))]);}
class BookDetail extends StatelessWidget{final Book book;const BookDetail(this.book,{super.key});@override Widget build(BuildContext c)=>Scaffold(backgroundColor:ink,appBar:AppBar(backgroundColor:ink,foregroundColor:Colors.white),body:Padding(padding:const EdgeInsets.all(24),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Center(child:Container(width:160,height:220,decoration:BoxDecoration(border:Border.all(color:gold),borderRadius:BorderRadius.circular(14)),child:const Icon(Icons.auto_stories,color:gold,size:80))),const SizedBox(height:22),Text(book.title,style:const TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.bold)),Text(book.author,style:const TextStyle(color:Colors.white70,fontSize:17)),const SizedBox(height:10),Text('★★★★★  ${book.category}',style:const TextStyle(color:gold)),const SizedBox(height:16),Text('₺${book.price}',style:const TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.bold)),const Spacer(),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>PreviewPage(book))),style:OutlinedButton.styleFrom(foregroundColor:Colors.white,side:const BorderSide(color:gold)),child:const Text('İlk 10 Sayfa'))),const SizedBox(width:12),Expanded(child:FilledButton(onPressed:()=>ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Sepete eklendi'))),style:FilledButton.styleFrom(backgroundColor:gold,foregroundColor:Colors.black),child:const Text('Sepete Ekle')))])])));}
class PreviewPage extends StatefulWidget{final Book book;const PreviewPage(this.book,{super.key});@override State<PreviewPage> createState()=>_PreviewPageState();}
class _PreviewPageState extends State<PreviewPage>{int page=1;@override Widget build(BuildContext c)=>Scaffold(backgroundColor:ink,appBar:AppBar(backgroundColor:ink,foregroundColor:Colors.white,title:Text('${widget.book.title}  $page/10')),body:Column(children:[Expanded(child:Container(margin:const EdgeInsets.all(16),padding:const EdgeInsets.all(28),color:const Color(0xFFFFFCF5),child:Text('Sayfa $page\n\nBu alan kitabın ücretsiz önizlemesidir. Yayında yalnızca ilk 10 sayfa gösterilecektir.',style:const TextStyle(fontSize:18,height:1.8)))),Padding(padding:const EdgeInsets.all(16),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[IconButton(onPressed:page>1?()=>setState(()=>page--):null,icon:const Icon(Icons.chevron_left,color:gold)),Text('$page / 10',style:const TextStyle(color:Colors.white)),IconButton(onPressed:page<10?()=>setState(()=>page++):null,icon:const Icon(Icons.chevron_right,color:gold))]))]));}
class AuthorPage extends StatelessWidget{const AuthorPage({super.key});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(24),children:[const Icon(Icons.edit_document,size:90,color:gold),const SizedBox(height:20),const Text('Eserinizi Bizimle Yayına Hazırlayın',textAlign:TextAlign.center,style:TextStyle(fontSize:27,fontWeight:FontWeight.bold)),const SizedBox(height:15),const Text('Eserinizi gönderin; inceleme, yayına hazırlık ve satış sürecini uygulamadan takip edin.',textAlign:TextAlign.center),...['Profesyonel editörlük desteği','Kapak ve tasarım çalışmaları','Basım süreci rehberliği','Satıştan gelir paylaşımı'].map((x)=>ListTile(leading:const Icon(Icons.check_circle,color:gold),title:Text(x))),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const ApplicationPage())),style:FilledButton.styleFrom(backgroundColor:gold,foregroundColor:Colors.black),child:const Text('Başvuru Yap'))]);}
class ApplicationPage extends StatelessWidget{const ApplicationPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Eser Başvurusu')),body:ListView(padding:const EdgeInsets.all(22),children:[const TextField(decoration:InputDecoration(labelText:'Eser Adı',border:OutlineInputBorder())),const SizedBox(height:15),const TextField(maxLines:6,decoration:InputDecoration(labelText:'Eser Hakkında',border:OutlineInputBorder())),const SizedBox(height:15),OutlinedButton.icon(onPressed:()=>ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Dosya yükleme backend bağlantısında etkinleşecek.'))),icon:const Icon(Icons.upload_file),label:const Text('PDF / Word Dosyası Seç')),FilledButton(onPressed:()=>ScaffoldMessenger.of(c).showSnackBar(const SnackBar(content:Text('Başvuru taslağı kaydedildi.'))),child:const Text('Devam Et'))]));}
class CartPage extends StatelessWidget{const CartPage({super.key});@override Widget build(BuildContext c)=>const ListView(children:[Header('Sepetim'),ListTile(title:Text('Sepetiniz'),subtitle:Text('Satın alma altyapısı sonraki aşamada bağlanacak.'))]);}
class AccountPage extends StatelessWidget{const AccountPage({super.key});@override Widget build(BuildContext c)=>ListView(children:[const Header('Hesabım'),for(final x in const ['Siparişlerim','Favorilerim','Kütüphanem','Başvurularım','Gelir Raporu','Adreslerim','Bildirimler','Ayarlar','Yardım & İletişim'])ListTile(title:Text(x),trailing:const Icon(Icons.chevron_right))]);}
